version: '2'

services:
  mongodb:
    container_name: mongodb
    image: docker.io/bitnami/mongodb:6.0
    ports:
      - "27017:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_USERNAME=app
      - MONGODB_PASSWORD=app
      - MONGODB_DATABASE=picpay_db
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local
